# Generated by Django 2.1.3 on 2019-02-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0003_auto_20190206_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='down_count',
            field=models.PositiveIntegerField(default=0, verbose_name='踩数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='up_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
