# Generated by Django 2.1.3 on 2019-02-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0004_auto_20190206_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
