# Generated by Django 2.1.3 on 2019-02-15 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0005_auto_20190208_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app001.Article', verbose_name='关联的文章标题'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='content',
            field=models.TextField(verbose_name='文章具体内容'),
        ),
    ]
