# Generated by Django 2.1.3 on 2019-02-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0006_auto_20190215_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
